# -*- coding: utf-8 -*-
"""Visualization-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11s6nFzDL_L4QRcSvcMrLPxaNwXD8jcgS

# **Titanic Data Visualization**
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

import warnings
warnings.filterwarnings("ignore")

"""# **Loading Dataset**"""

data = pd.read_csv('/content/train.csv') # provide train.csv through chat window
data.head()

"""# **Data Types**"""

data.info()

data.shape

data.describe()

"""# **Proportion of targate (survived)**"""

data.groupby('Survived')['PassengerId'].count()
# 549 passangers could not survive, 342 - survived
# try groupby - Sex,groupby(['Survived','Sex'])

pd.crosstab(data['Survived'],data['Sex'])

"""# **Visual Exploration**"""

pd.crosstab(data['Survived'],data['Sex']).plot(kind='bar')

plt.figure(figsize=(10,5))
sns.boxplot(x='Survived', y="Age",  data=data);

plt.figure(figsize=(10,8))
sns.barplot(x='Sex', y="Survived",  data=data);

plt.figure(figsize=(11,5))
sns.boxplot(x="Sex", y="Age", hue="Survived", data=data);

sns.barplot(x="Pclass", y="Survived", data=data);

sns.barplot(x="Pclass", y="Survived",hue="Sex", data=data);

sns.barplot(x="SibSp", y="Survived", data=data);

sns.barplot(x="Parch", y="Survived", data=data);

data.loc[data['Survived']==1,"Age"] # age col contains some na values

survived = data.loc[data['Survived']==1,"Age"].dropna()
sns.distplot(survived)
# plt.title=("Survived");

not_survived = data.loc[data['Survived']==0,"Age"].dropna()
sns.distplot(not_survived)
# plt.title=("Not Survived");

sns.pairplot(data); #scatterplot of all variables

# Pclass vs Survive
grid = sns.FacetGrid(data, col='Survived', row='Pclass', size=2.4, aspect=1.5)
grid.map(plt.hist, 'Age', alpha=.5, bins=20)
grid.add_legend()

figbi, axesbi = plt.subplots(2, 4, figsize=(18, 10))
data.groupby('Pclass')['Survived'].mean().plot(kind='barh',ax=axesbi[0,0],xlim=[0,1])
data.groupby('SibSp')['Survived'].mean().plot(kind='barh',ax=axesbi[0,1],xlim=[0,1])
data.groupby('Parch')['Survived'].mean().plot(kind='barh',ax=axesbi[0,2],xlim=[0,1])
data.groupby('Sex')['Survived'].mean().plot(kind='barh',ax=axesbi[0,3],xlim=[0,1])
data.groupby('Embarked')['Survived'].mean().plot(kind='barh',ax=axesbi[1,0],xlim=[0,1])
sns.boxplot(x="Survived", y="Age", data=data,ax=axesbi[1,1])
sns.boxplot(x="Survived", y="Fare", data=data,ax=axesbi[1,2])
plt.show()
figbi.savefig("my1stfig.png")
from google.colab import files
files.download("my1stfig.png")

